# coding=utf-8

PHOTO_SHOW_STATUS_DISPLAY = 1
PHOTO_SHOW_STATUS_NO_DISPLAY = 0

PHOTO_SHOW_STATUS_LIST = [PHOTO_SHOW_STATUS_DISPLAY, PHOTO_SHOW_STATUS_NO_DISPLAY]

PHOTO_SHOW_STATUS_OPTIONS = (
    ("展示", PHOTO_SHOW_STATUS_DISPLAY),
    ("不展示", PHOTO_SHOW_STATUS_NO_DISPLAY),
)

