# Generated by Django 2.1.1 on 2019-01-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edit_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '富文本'), (1, 'markdown'), (2, 'json'), (3, '其他')], default=0),
        ),
    ]
