# Generated by Django 2.1.1 on 2018-12-07 16:07

import account.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('oid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=48, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('nickname_change_time', models.DateTimeField(blank=True, null=True)),
                ('remark_name', models.CharField(blank=True, max_length=16, null=True)),
                ('avatar', models.URLField(blank=True, max_length=256, null=True)),
                ('avatar_change_time', models.DateTimeField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cms', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('register_type', models.PositiveSmallIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'permissions': (('can_login_cms', '能登录CMS'), ('cms_manage_dashboard', 'CMS-管理数据'), ('cms_manage_self_article', 'CMS-管理自己的文章'), ('cms_manage_all_article', 'CMS-管理全部的文章'), ('cms_manage_article_tags', 'CMS-管理所有标签'), ('cms_manage_photo_wall', 'CMS-管理图片墙'), ('cms_manage_timeline', 'CMS-管理时间线'), ('cms_manage_banner_slide_show', 'CMS-管理横幅-首页轮播'), ('cms_manage_permissions', 'CMS-管理用户权限'), ('cms_manage_account', 'CMS-管理所有账号')),
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('avatar', models.URLField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeiBoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('avatar', models.URLField(blank=True, max_length=1024, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
