# Generated by Django 2.1.1 on 2019-01-08 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefaultAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('open_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('avatar_url', models.CharField(max_length=256)),
                ('sort_id', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_change_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname_change_time',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_change_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname_change_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
