# Generated by Django 2.1.1 on 2018-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('open_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('sort_no', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('description', models.CharField(default='', max_length=128)),
                ('img', models.CharField(default='', max_length=256)),
                ('link', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
