# Generated by Django 2.1.1 on 2019-01-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='content',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='timelineline',
            name='content',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='timelineline',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
