# Generated by Django 2.1.1 on 2019-01-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20190102_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='content',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='timelineline',
            name='content',
            field=models.CharField(default='', max_length=512),
        ),
    ]
