# Generated by Django 2.1.1 on 2018-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('open_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=256)),
                ('sort_no', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[('展示', 1), ('不展示', 0)], default=0)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('original_datetime', models.DateTimeField(blank=True, null=True)),
                ('original_place', models.CharField(blank=True, max_length=32, null=True)),
                ('source_name', models.CharField(blank=True, max_length=32, null=True)),
                ('source_link', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
